### ISSUE TITLE
[fivemqueue - ERROR] - SessionProcessing() - Handle Session File Update

### ISSUE THREAD

**Issue by SteffenFriis** [anderscripts/FiveM_Queue#10]
Installed and it shows no error.

Once the first player connects it keeps spamming

_[fivemqueue - ERROR] - SessionProcessing() - Handle Session File Update_

**Comment by anderscripts** [comment]
I've only been able to repo this problem if I delete the session.json file while the server and fivemqueue resource are running.  Delete session.json file between server restarts, starting fivemqueue again will recreate the file from scratch:

```
                if (!File.Exists(session))
                {
                    File.WriteAllText(session, JsonConvert.SerializeObject(sessionAccounts));
                }
                jsonSession = File.ReadAllText(session);
                sessionAccounts = JsonConvert.DeserializeObject<List<SessionAccount>>(jsonSession);
```

--- version 1.1.0 release will not include session.json and will solve this problem for you if it persists.
