### ISSUE TITLE
Could not connect to session provider. (Queue putting players through even when full)

### ISSUE THREAD

**Issue by Yufai** [anderscripts/FiveM_Queue#15]
Queue is connecting players to the server even when full. It used to be a very rare issue, and restarting the server would resolve it, however, starting from a couple hours ago from this post, it has been a very common reoccurring issue.

**Comment by username9381** [comment]
What is your Discord?

**Comment by Local9** [comment]
I wonder if there was a fix for this, been experiencing it when at high loads.
