### ISSUE TITLE
Admin Menu

### ISSUE THREAD

**Issue by ghost** [anderscripts/FiveM_Queue#20]
The /q_session does not close for me.

**Comment by ghost** [comment]
If you fixed it can you let me know on discord? :D - DuhItzRik#0909

**Comment by anderscripts** [comment]
Testing on windows build 1069

https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/1069-f86146792fdf3bc1bd3efe978468b476f4cbf934/

**Comment by anderscripts** [comment]
Testing on fresh server/client build 1069 works fine.

Close q_session panel with the close button, ESC, or Backspace key.
