### ISSUE TITLE
Bug: When released in queue

### ISSUE THREAD

**Issue by mickeygeecom** [anderscripts/FiveM_Queue#26]
A user was in queue for 15 minutes, when it became his turn this turned up. Sad if I doesnt rejoin quick enough, then he'll have to start all over again.
![image0](https://user-images.githubusercontent.com/5321009/54521236-cf03bb00-496a-11e9-9383-e4a28ee250e4.jpg)
This sometimes happens when in queue and you get 'released'

An element from FiveM stated this:
![image](https://user-images.githubusercontent.com/5321009/54521303-f064a700-496a-11e9-85f4-044518444aec.png)

**Comment by anderscripts** [comment]
Solved by fivem:

server/onesync: don't reassign slot IDs if a client already has one
https://github.com/citizenfx/fivem/commit/fee19ff43071dec5c95c6602041b117adab95733
