### ISSUE TITLE
MySQL Support for Queue Priorities

### ISSUE THREAD

**Issue by Jarrrk** [anderscripts/FiveM_Queue#29]
Currently with the fivemqueue system, it uses a flat-file system to store queue priorities, which also is pretty messy considering it also creates a separate JSON file for each user, additionally this also causes issues for servers/developer that use a build and CI system for deployments etc.

As much as I would love to create a PR for this I simply don't have the experience I used to with C# and can't provide anything useful. What I would suggest is the ability for the queue to interface with a table to be able to retrieve priority data, with the ability to specify which user identifier (steam/license/ip) to reference against with a simple integer value in the associated row.

Many thanks, love the queue system!

**Comment by anderscripts** [comment]
feature update in progress

**Comment by Death-Avenger** [comment]
> feature update in progress

I would be extremely interested in how you implement this. Is there an ETA for your planned update?

**Comment by anderscripts** [comment]
This is complete and in testing in a live environment.  Release candidate will be approved soon.

**Comment by Jarrrk** [comment]
@anderscripts thanks for the update!

One thing that would be incredibly useful would be a `refresh_priorities` command that could pull down the priorities from the table if more have been added in externally, is this something that could be added? 

If not I'll PR it.
