### ISSUE TITLE
Priority Problem

### ISSUE THREAD

**Issue by BryBTG** [anderscripts/FiveM_Queue#31]
![image](https://user-images.githubusercontent.com/50550050/60819057-6d918180-a1d1-11e9-8dda-5565bde2ebe1.png)

I restarted my server i labeled my account as 1 but im still on last line.

**Comment by anderscripts** [comment]
Unsure if this is an issue but there will be a new release in coming days that will eliminate the whole offline priority system that causes people to need to cancel and rejoin queue.
