### ISSUE TITLE
[queue - ERROR] - UpdateStates()

### ISSUE THREAD

**Issue by zek0** [anderscripts/FiveM_Queue#39]
After FxServer updates:

[queue]: NEW -> QUEUE -> (Public) af0ee539d69c0a9d227ba070976d8ccf72cc21de
[queue]: QUEUE -> LOADING -> (Reserved3) af0ee539d69c0a9d227ba070976d8ccf72cc21de
[queue - ERROR] - UpdateStates()
[queue - ERROR] - UpdateStates()
[queue - ERROR] - UpdateStates()
[queue - ERROR] - UpdateStates()
[queue - ERROR] - UpdateStates()
[queue - ERROR] - UpdateStates()
[queue - ERROR] - UpdateStates()
[queue - ERROR] - UpdateStates()
[queue - ERROR] - UpdateStates()
[queue - ERROR] - UpdateStates()
[queue - ERROR] - UpdateStates()
[queue - ERROR] - UpdateStates()
[queue - ERROR] - UpdateStates()
[queue - ERROR] - UpdateStates()
[queue - ERROR] - UpdateStates()
[queue - ERROR] - UpdateStates()
[queue - ERROR] - UpdateStates()
[queue - ERROR] - UpdateStates()
[queue - ERROR] - UpdateStates()
[queue]: LOADING -> GRACE -> af0ee539d69c0a9d227ba070976d8ccf72cc21de

**Comment by wittyphantom333** [comment]
same issue with most recent version of cfx linux 2949.  Issue happens while a player is loading, from connect until character select it spams this and then stops once they login

**Comment by anderscripts** [comment]
@wittyphantom333 @zek0 Is this still happening on more recent versions of linux artifacts?

**Comment by zek0** [comment]
> @wittyphantom333 @zek0 Is this still happening on more recent versions of linux artifacts?

Yes still happen on latest windows artifact 2969.

**Comment by anderscripts** [comment]
@zek0 @wittyphantom333 - Please try the [release](https://github.com/anderscripts/FiveM_Queue/releases/download/v1.1.0/fivemqueue.rar) now that I've made a change and let me know if this error is still happening.  You really only need to replace your exiting Server_Queue.net.dll with the file now in the release rar.

**Comment by wittyphantom333** [comment]
@anderscripts working now.  Thank you

**Comment by anderscripts** [comment]
No problem, for your info this was caused by an event being triggered that one of the test servers had asked for in the vanilla release, so it was no harm removing it as a temporary fix. In a future release I'll update the libraries included in the project to resolve issues with triggering client events.
