### ISSUE TITLE
People stuck in queue when it hits 32 players

### ISSUE THREAD

**Issue by GrizzlyRP** [anderscripts/FiveM_Queue#40]
Works great, only issue I seem to have is that people get stuck in a queue at 32 players, even tho its set to 54. I have to manually reload the config, then they can join. Also the queue name doesn’t work, it just sets your server to Default FXServer.

**Comment by anderscripts** [comment]
@GrizzlyRP 
This will happen if you start fivemqueue before the lines you have in your server.cfg to set the sv_maxclients and sv_hostname

start your resources at the bottom of your server.cfg file after you've done everything else to configure the server
